server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ehcahe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    #    org.springframework.web: trace
    org.springframework.web: info
    com:
      roncoo:
        product:
          ha: info